### ISSUE TITLE
$input.autocomplete is not a function

### ISSUE THREAD

**Issue by OskarD** [shobute/datalist#1]
I tried to include your library on my website and got this error:

datalist.js:19 Uncaught TypeError: $input.autocomplete is not a function

**Comment by shobute** [comment]
Hi @OskarD, this requires [Jquery UI](https://jqueryui.com/).

**Comment by OskarD** [comment]
Ok, thanks :) Maybe it should be mentioned somewhere?

**Comment by shobute** [comment]
Good point, I have updated the README to make this clearer. Thanks. :)
